import React from 'react'
import { ArrowRight, Linkedin, Target, Compass, ShieldCheck, Sun, Users, Zap, Rocket, Home, Star, Building2 } from 'lucide-react'
import teamImage from '../assets/team/team.png'

const team = [
  ['Deepak Singh', 'Co-Founder', 'https://www.zxsolarenergies.com/images/Myphoto/single%20photo%202.jpg', 'https://www.linkedin.com/in/deepak-singh-4a7988217'],
  ['Meenu Pandey', 'CFO', 'https://www.zxsolarenergies.com/images/Myphoto/meenu.jpeg', 'https://www.linkedin.com/in/meenu-pandey-353a26294'],
  ['Abhishek Sen', 'National Sales Manager', 'https://www.zxsolarenergies.com/images/Myphoto/single%20photo%204.jpg', 'https://www.linkedin.com/in/abhishek-sen-7b604024a'],
  ['Ritu Shrivastav', 'Head HRBP', 'https://www.zxsolarenergies.com/images/Myphoto/single%20photo%203.jpg', '#'],
  ['Jitendra Panday', 'Technical Expert', 'https://www.zxsolarenergies.com/images/Myphoto/Single%20Photo%206.jpg', '#'],
  ['Dharmendra Gujare', 'Regional Sales Expert', 'https://www.zxsolarenergies.com/images/Myphoto/single%20photo%201.jpg', 'https://www.linkedin.com/in/dharmendra-gujare-417974282'],
]

const milestones = [
  ['2022', 'Zxsolar Began', 'Founded with a vision to make solar energy accessible to every home and business in India.', Rocket],
  ['2023', '100+ Clients Solarised', 'Reached the milestone of 100+ satisfied clients across residential and commercial sectors.', Home],
  ['2024', '500+ Happy Customers', 'Growing family of 500+ happy customers with 4.8/5 average rating.', Star],
  ['2024', '50+ Housing Societies', 'Trusted by 50+ housing societies for community solar solutions.', Building2],
]

const stats = [['300+', 'Trusted Homeowners', Home], ['30+', 'Trusted Companies', Building2], ['10 MW', 'Rooftop Experience', Zap], ['50+', 'Team Members', Users]]

export default function AboutPage() {
  return <div className="bg-[#f7faf7] text-[#17251e]">
    <section className="relative overflow-hidden bg-[#123426] px-6 py-20 text-white lg:px-16 lg:py-28"><div className="absolute inset-0 opacity-20 solar-grid" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="mb-5 flex items-center gap-2 text-sm font-bold uppercase tracking-[0.2em] text-[#b5d941]"><Sun className="h-4 w-4" /> About us</p><h1 className="max-w-xl text-5xl font-extrabold leading-[1.05] sm:text-6xl">We make rooftop solar <span className="text-[#b5d941]">with integrity.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/75">Zxsolar Energies is a team of 50+ engineers, MBAs, scientists and creative thinkers driven by the single vision of accelerating adoption of solar in India.</p><a href="#vision" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#b5d941] px-6 py-3 font-bold text-[#123426] transition hover:bg-white">Explore our story <ArrowRight className="h-4 w-4" /></a></div><div className="relative"><img src={teamImage} alt="Zxsolar Energies team" className="h-[420px] w-full rounded-[2rem] object-cover object-[center_top] shadow-2xl" /><div className="absolute -bottom-5 -left-5 rounded-2xl bg-white p-5 text-[#17251e] shadow-xl"><p className="text-3xl font-extrabold text-[#6eae22]">50+</p><p className="text-sm font-bold">Team Members<br />Engineers & Innovators</p></div></div></div></section>
    <section id="vision" className="px-6 py-20 lg:px-16 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#6eae22]">Our vision</p><h2 className="mt-3 text-4xl font-extrabold sm:text-5xl">Pioneering Solar Excellence</h2><p className="mt-5 text-lg leading-8 text-slate-600">Our everyday goal is simple: to make rooftop solar accessible to all. We focus on your happiness, which keeps us constantly innovating.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[['Our Vision','Our vision is to make clean energy affordable and accessible to every home and business in India.',Compass],['Our Mission','Our mission is to make the solar generation industry more organized and professional.',Target],['Our Method','Our method is to infuse transparency and trust in every step of your solar journey.',ShieldCheck]].map(([title,text,Icon]) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><Icon className="h-8 w-8 text-[#6eae22]" /><h3 className="mt-6 text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div><div className="mt-14 grid grid-cols-2 gap-5 border-t border-slate-200 pt-10 md:grid-cols-4">{stats.map(([number,label,Icon]) => <div key={label}><Icon className="h-6 w-6 text-[#6eae22]" /><p className="mt-3 text-3xl font-extrabold">{number}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div></div></section>
    <section className="bg-white px-6 py-20 lg:px-16"><div className="mx-auto max-w-7xl"><div className="mb-12"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#6eae22]">Our team</p><h2 className="mt-3 text-4xl font-extrabold">Meet Our Leadership</h2><p className="mt-3 text-slate-600">Passionate professionals dedicated to powering India's solar future.</p></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{team.map(([name,role,image,linkedin]) => <article key={name} className="group overflow-hidden rounded-2xl border border-slate-200 bg-[#f7faf7]"><div className="relative aspect-[4/3] overflow-hidden bg-[#edf5e9]"><img src={image} alt={name} className="h-full w-full object-contain object-top" /><a href={linkedin} target="_blank" rel="noreferrer" aria-label={`LinkedIn profile of ${name}`} className="absolute bottom-4 right-4 rounded-full bg-white p-3 text-[#123426] shadow-lg transition hover:bg-[#b5d941]"><Linkedin className="h-4 w-4" /></a></div><div className="p-5"><h3 className="text-xl font-bold">{name}</h3><p className="mt-1 text-sm font-semibold text-[#6eae22]">{role}</p></div></article>)}</div></div></section>
    <section id="milestones" className="bg-[#edf5e9] px-6 py-20 lg:px-16"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#6eae22]">Our journey</p><h2 className="mt-3 text-4xl font-extrabold">Our Milestones</h2><p className="mt-3 text-slate-600">Tracking our growth and impact in the solar industry.</p><div className="mt-12 grid gap-5 md:grid-cols-4">{milestones.map(([year,title,text,Icon]) => <div key={title} className="border-t-2 border-[#b5d941] pt-5"><Icon className="h-7 w-7 text-[#6eae22]" /><p className="mt-5 text-sm font-bold text-[#6eae22]">{year}</p><h3 className="mt-2 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></div></section>
  </div>
}
